package com.bernaferrari.renetguard.demo

val MOCK_APPS: List<AppRule> = listOf(
    AppRule(
        id = "instagram",
        name = "Instagram",
        packageName = "com.instagram.android",
        iconColor = "#E1306C",
        iconGlyph = "IG",
        wifiBlocked = true,
        mobileBlocked = true,
    ),
    AppRule(
        id = "tiktok",
        name = "TikTok",
        packageName = "com.zhiliaoapp.musically",
        iconColor = "#010101",
        iconGlyph = "TT",
        wifiBlocked = true,
        mobileBlocked = false,
    ),
    AppRule(
        id = "chrome",
        name = "Chrome",
        packageName = "com.android.chrome",
        iconColor = "#4285F4",
        iconGlyph = "Ch",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "spotify",
        name = "Spotify",
        packageName = "com.spotify.music",
        iconColor = "#1DB954",
        iconGlyph = "Sp",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "whatsapp",
        name = "WhatsApp",
        packageName = "com.whatsapp",
        iconColor = "#25D366",
        iconGlyph = "WA",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "gmail",
        name = "Gmail",
        packageName = "com.google.android.gm",
        iconColor = "#EA4335",
        iconGlyph = "Gm",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "youtube",
        name = "YouTube",
        packageName = "com.google.android.youtube",
        iconColor = "#FF0000",
        iconGlyph = "YT",
        wifiBlocked = true,
        mobileBlocked = true,
    ),
    AppRule(
        id = "slack",
        name = "Slack",
        packageName = "com.Slack",
        iconColor = "#4A154B",
        iconGlyph = "Sl",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "netflix",
        name = "Netflix",
        packageName = "com.netflix.mediaclient",
        iconColor = "#E50914",
        iconGlyph = "Nf",
        wifiBlocked = false,
        mobileBlocked = true,
    ),
    AppRule(
        id = "twitter",
        name = "X",
        packageName = "com.twitter.android",
        iconColor = "#14171A",
        iconGlyph = "X",
        wifiBlocked = true,
        mobileBlocked = true,
    ),
    AppRule(
        id = "discord",
        name = "Discord",
        packageName = "com.discord",
        iconColor = "#5865F2",
        iconGlyph = "Dc",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "telegram",
        name = "Telegram",
        packageName = "org.telegram.messenger",
        iconColor = "#26A5E4",
        iconGlyph = "Tg",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "maps",
        name = "Maps",
        packageName = "com.google.android.apps.maps",
        iconColor = "#34A853",
        iconGlyph = "Mp",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "camera",
        name = "Camera",
        packageName = "com.android.camera",
        iconColor = "#5F6368",
        iconGlyph = "Ca",
        wifiBlocked = false,
        mobileBlocked = false,
        system = true,
    ),
    AppRule(
        id = "files",
        name = "Files",
        packageName = "com.google.android.apps.nbu.files",
        iconColor = "#1A73E8",
        iconGlyph = "Fl",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "reddit",
        name = "Reddit",
        packageName = "com.reddit.frontpage",
        iconColor = "#FF4500",
        iconGlyph = "Rd",
        wifiBlocked = true,
        mobileBlocked = false,
    ),
    AppRule(
        id = "linkedin",
        name = "LinkedIn",
        packageName = "com.linkedin.android",
        iconColor = "#0A66C2",
        iconGlyph = "Li",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "uber",
        name = "Uber",
        packageName = "com.ubercab",
        iconColor = "#000000",
        iconGlyph = "Ub",
        wifiBlocked = false,
        mobileBlocked = false,
    ),
    AppRule(
        id = "amazon",
        name = "Amazon",
        packageName = "com.amazon.mShop.android.shopping",
        iconColor = "#FF9900",
        iconGlyph = "Am",
        wifiBlocked = false,
        mobileBlocked = true,
    ),
    AppRule(
        id = "system",
        name = "Android System",
        packageName = "android",
        iconColor = "#3DDC84",
        iconGlyph = "An",
        wifiBlocked = false,
        mobileBlocked = false,
        system = true,
    ),
)

val INITIAL_LOGS: List<LogEntry> = listOf(
    LogEntry(
        id = "log-1",
        appId = "instagram",
        appName = "Instagram",
        protocol = LogProtocol.TCP,
        destination = "graph.instagram.com",
        port = 443,
        allowed = false,
        time = "14:32:08",
    ),
    LogEntry(
        id = "log-2",
        appId = "youtube",
        appName = "YouTube",
        protocol = LogProtocol.TCP,
        destination = "i.ytimg.com",
        port = 443,
        allowed = false,
        time = "14:31:54",
    ),
    LogEntry(
        id = "log-3",
        appId = "chrome",
        appName = "Chrome",
        protocol = LogProtocol.UDP,
        destination = "dns.google",
        port = 53,
        allowed = true,
        time = "14:31:41",
    ),
    LogEntry(
        id = "log-4",
        appId = "tiktok",
        appName = "TikTok",
        protocol = LogProtocol.TCP,
        destination = "api.tiktokv.com",
        port = 443,
        allowed = false,
        time = "14:31:22",
    ),
    LogEntry(
        id = "log-5",
        appId = "whatsapp",
        appName = "WhatsApp",
        protocol = LogProtocol.TCP,
        destination = "g.whatsapp.net",
        port = 443,
        allowed = true,
        time = "14:30:59",
    ),
    LogEntry(
        id = "log-6",
        appId = "twitter",
        appName = "X",
        protocol = LogProtocol.TCP,
        destination = "api.twitter.com",
        port = 443,
        allowed = false,
        time = "14:30:33",
    ),
    LogEntry(
        id = "log-7",
        appId = "spotify",
        appName = "Spotify",
        protocol = LogProtocol.TCP,
        destination = "apresolve.spotify.com",
        port = 443,
        allowed = true,
        time = "14:30:11",
    ),
    LogEntry(
        id = "log-8",
        appId = "reddit",
        appName = "Reddit",
        protocol = LogProtocol.TCP,
        destination = "reddit.map.fastly.net",
        port = 443,
        allowed = false,
        time = "14:29:48",
    ),
)

fun createDefaultState(): DemoState = DemoState(
    firewallEnabled = true,
    tab = DemoTab.Home,
    appsFilter = AppsFilter.All,
    searchQuery = "",
    selectedAppId = null,
    apps = MOCK_APPS,
    logs = INITIAL_LOGS,
    settings = DemoSettings(),
)